[package]
name = "app-main"
description = "Main image view app, manages windows, images, and UI."
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
clap = { workspace = true }
glium = "0.36.0"
image = "0.25.6"
winit = "0.30.12"

[[bin]]
name = "app-main"
path = "src/main.rs"
test = true
